=== cfgteam30/webtech/cars.dtd
<!DOCTYPE cars_catalog>
[
    <!ELEMENT cars_catalog(car+)
    <!ELEMENT car (make,model,year,color,engine,number_of_doors,transmission_type,accessories)
    <!ELEMENT make (#PCDATA)>
    <!ELEMENT model (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT color (#PCDATA)>
    <!ELEMENT engine (number_of_cylinders,fuel_system)>
    <!ELEMENT number_of_doors (#PCDATA)>
    <!ELEMENT fuel_system (#PCDATA)>
    <!ELEMENT transmission_type (#PCDATA)>
    <!ELEMENT number_of_cylinders (#PCDATA)>
    <!ELEMENT accessories (#PCDATA)>
    <!ENTITY f "Ford">
    <!ENTITY h "Honda">
    <!ENTITY t "Toyota">
    <!ATTLIST accessories 
    radio (true|false) #REQUIRED>
    <!ATTLIST accessories air_conditioning CDATA #REQUIRED>
    <!ATTLIST accessories power_windows CDATA #REQUIRED>
    <!ATTLIST accessories power_steering CDATA #REQUIRED>
    <!ATTLIST accessories power_brakes CDATA #REQUIRED>
]

=== cfgteam30/webtech/x1.xml
<!DOCTYPE cars_catalog SYSTEM "cars.dtd">
<?xml-stylesheet type="text/css" href="s1.css"?>
<cars_catalog>
    <car>
        <make>xxx</make>
        <year>1999</year>
        <color>bule</color>
        <engine>
            <number_of_cylinders>8</number_of_cylinders>
            <fuel_system>yyy</fuel_system>
        </engine>
        <number_of_doors>4</number_of_doors>
        <transmission_type>automatic</transmission_type>
        <accessories radio="yes" air_conditioning="yes" power_brakes="yes" power_steering="yes" power_windows="yes"/>
    </car>
</cars_catalog>
